[package]
name = "glfw-test"
version = "0.1.0"
authors = ["ChoWonmin <0108257@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"

